### ISSUE TITLE
Please make the Irem M72 Core SIDI compatible

### ISSUE THREAD

**Issue by alessioscand** [Gehstock/Mist_FPGA_Cores#38]
Hello and thank you so much for this awesome core.

Unfortunately it doesn't compile on SiDi (a MiST-derived board), because the Altera Cyclone IV EP4CE22 is about 10% smaller than the FPGA on MiST, so something should be optimized/omitted. 

IIRC already omitting the i8751 MCU with conditionals would allow to run the two M84 games (R-Type II and Hammerin' Harry) while Gallop - Armed Police Unit (M72) would run without playing samples.

If it is possible to go further, on the Arcade Projects forum there are interesting informations about the bypass of the MCU and it is also available a patched romset.

Useful links:

Port from MiST to SiDi 
https://github.com/ManuFerHi/SiDi-FPGA/blob/master/Hardware/Mist2DiDi.txt

Bypassing the i8751MCU on IREM Multi M72 (Arcade Projects forum thread) 
https://www.arcade-projects.com/threads/irem-m72-multi-sales-installation-and-support.19869/

Patched romset for IREM M72 Multi
https://www.arcade-projects.com/threads/irem-m72-roll-up-pack-all-roms-for-the-apocalypse-m72-multi.17562/

IREM M84 conversions (Arcade Projects forum thread) 
https://www.arcade-projects.com/threads/irem-m84-conversions.4775/page-6

Of course, any option would be better than nothing. Thanks so much for your time.

**Comment by gyurco** [comment]
If you can create MRAs for the M84 converted versions, then building a core without the i8751 is almost trivial.

**Comment by alessioscand** [comment]
Hello, and happy holidays!
I asked around, and apparently the M84 converted roms are not publicly available yet.

If it's not an issue for the Master branch, would it be possible to put a conditional in the source code to omit the i8751 MCU on SiDi and/or smaller cyclones? This would allow at least Hammerin' Harry and R-Type II to work.

I have prepared (hopefully I haven't made any mistakes) the .qsf and .qpf files for SiDi, available here:
https://drive.google.com/drive/folders/1f_6_G_zy4g8kxf15ecouOP4Nwuk-gqhf?usp=sharing

Thank you so much!

**Comment by alessioscand** [comment]
Hello,
it seems that the core is buildable "as is" with Intel Quartus ver. 13 (the one I'm using right now is 17.1).
I'm downloading 13.1 Web Edition, if it works I'll close the issue.  :)

Thank you

**Comment by alessioscand** [comment]
```
Flow Status	Successful - Wed Jan 11 23:11:10 2023
Quartus II 64-Bit Version	13.1.0 Build 162 10/23/2013 SJ Web Edition
Revision Name	IremM72_Sidi
Top-level Entity Name	IremM72_MiST
Family	Cyclone IV E
Device	EP4CE22F17C8
Timing Models	Final
Total logic elements	22,234 / 22,320 ( 100 % )
Total combinational functions	21,964 / 22,320 ( 98 % )
Dedicated logic registers	7,166 / 22,320 ( 32 % )
Total registers	7234
Total pins	70 / 154 ( 45 % )
Total virtual pins	0
Total memory bits	459,174 / 608,256 ( 75 % )
Embedded Multiplier 9-bit elements	85 / 132 ( 64 % )
Total PLLs	1 / 4 ( 25 % )
```

The core compiles fine as-is with Quartus II 64-Bit Version 13.1.0.
It occupies 100% of the Cyclone IV so any possible optimization will be welcome, but it works, so I'm closing the issue.
Thank you!
